"""Self-contained HTML analysis-report builder.

Strings together the artefacts an OpenFlo session produces — a metadata header,
sample summary, population-statistics table, embedded figures, and the
provenance/audit trail — into ONE portable ``.html`` file (images embedded as
base64 data URIs, so there are no sidecar files to lose). Pure / stdlib +
matplotlib only; the GUI assembles the sections, this module renders them.
"""
from __future__ import annotations

import base64
import html
import io


def figure_to_data_uri(fig, fmt='png', dpi=150):
    """Render a matplotlib Figure to a base64 ``data:`` URI (default PNG), for
    embedding directly in an ``<img src=...>`` with no external file."""
    buf = io.BytesIO()
    fig.savefig(buf, format=fmt, dpi=dpi, bbox_inches='tight')
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')
    mime = 'image/svg+xml' if fmt == 'svg' else f'image/{fmt}'
    return f'data:{mime};base64,{b64}'


def figure_html(fig, fmt='png', dpi=150, alt=''):
    """An ``<img>`` tag with the figure embedded as a data URI."""
    return (f'<img alt="{html.escape(alt)}" '
            f'src="{figure_to_data_uri(fig, fmt=fmt, dpi=dpi)}">')


def df_to_html_table(df, float_format='{:.4g}', max_rows=None):
    """Render a DataFrame to an HTML table (escaped, NaNs blanked). Truncates
    to ``max_rows`` with a note when given."""
    note = ''
    if max_rows is not None and len(df) > max_rows:
        note = (f'<p class="note">Showing {max_rows} of {len(df)} rows.</p>')
        df = df.head(max_rows)

    def fmt(v):
        try:
            import math
            if isinstance(v, float) and math.isnan(v):
                return ''
        except Exception:
            pass
        if isinstance(v, float):
            try:
                return html.escape(float_format.format(v))
            except Exception:
                return html.escape(str(v))
        return html.escape('' if v is None else str(v))

    cols = list(df.columns)
    head = ''.join(f'<th>{html.escape(str(c))}</th>' for c in cols)
    body = []
    for _, row in df.iterrows():
        cells = ''.join(f'<td>{fmt(row[c])}</td>' for c in cols)
        body.append(f'<tr>{cells}</tr>')
    return (f'{note}<table><thead><tr>{head}</tr></thead>'
            f'<tbody>{"".join(body)}</tbody></table>')


_CSS = """
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  max-width:1100px;margin:24px auto;padding:0 16px;color:#1a1a1a;line-height:1.5}
h1{border-bottom:2px solid #333;padding-bottom:6px}
h2{margin-top:32px;border-bottom:1px solid #ddd;padding-bottom:4px}
.meta ul{list-style:none;padding:0;columns:2}
.meta li{margin:2px 0}
table{border-collapse:collapse;font-size:13px;margin:8px 0;width:100%}
th,td{border:1px solid #ccc;padding:3px 8px;text-align:right}
th{background:#f3f3f3;text-align:center}
td:first-child,th:first-child{text-align:left}
tbody tr:nth-child(even){background:#fafafa}
img{max-width:100%;height:auto;border:1px solid #eee;margin:8px 0}
.note{color:#777;font-size:12px;font-style:italic}
footer{margin-top:40px;color:#999;font-size:12px;border-top:1px solid #eee;
  padding-top:8px}
"""


def build_html_report(title, meta=None, sections=None):
    """Assemble the final HTML document.

    ``meta`` : ``{label: value}`` rendered as a header bullet list.
    ``sections`` : ordered list of ``{'heading': str, 'html': str}``.
    Returns the complete HTML string."""
    out = ['<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
           f'<title>{html.escape(title)}</title>',
           f'<style>{_CSS}</style></head><body>',
           f'<h1>{html.escape(title)}</h1>']
    if meta:
        out.append('<div class="meta"><ul>')
        for k, v in meta.items():
            out.append(f'<li><b>{html.escape(str(k))}:</b> '
                       f'{html.escape(str(v))}</li>')
        out.append('</ul></div>')
    for sec in (sections or []):
        out.append(f'<h2>{html.escape(str(sec.get("heading", "")))}</h2>')
        out.append(sec.get('html', ''))
    out.append('<footer>Generated by OpenFlo.</footer>')
    out.append('</body></html>')
    return '\n'.join(out)
