#!/usr/bin/env python
"""Emit a pip constraints file pinning every dependency to its declared FLOOR.

A range like `numpy>=2.0,<3` is a promise about versions nobody runs. pip
resolves to the newest thing that fits, so CI normally exercises the ceiling
and the floor is an untested assertion — the same "check that cannot fail"
shape this codebase keeps finding, in packaging form.

This reads the floors straight out of `pyproject.toml` and writes them as exact
pins, so `pip install openflo -c lowest.txt` installs the oldest combination we
claim to support. It is generated rather than hand-maintained on purpose:
widening a floor updates what CI tests, with no second place to remember.

Dependencies already pinned with `==` are emitted unchanged; anything with no
lower bound at all is skipped and reported, since there is nothing to test.

    python scripts/lowest_direct_requirements.py > lowest.txt
    pip install dist/openflo-*.whl -c lowest.txt
"""
from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

# name[extras] followed by the specifier set; environment markers are dropped
# (a marker cannot narrow a floor, only decide whether the dep applies).
_REQ = re.compile(r'^\s*([A-Za-z0-9._-]+)\s*(?:\[[^\]]*\])?\s*([^;]*)')


def floor_of(requirement: str) -> tuple[str, str | None]:
    """`('numpy', '2.0')` for `numpy>=2.0,<3`; `(name, None)` when unbounded."""
    match = _REQ.match(requirement)
    if not match:
        return requirement, None
    name, specs = match.group(1), match.group(2) or ''
    exact = re.search(r'==\s*([^\s,]+)', specs)
    if exact:
        return name, exact.group(1)
    lower = re.search(r'>=\s*([^\s,]+)', specs)
    return name, lower.group(1) if lower else None


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or '').splitlines()[0])
    ap.add_argument('--pyproject', default='pyproject.toml')
    ap.add_argument('--extra', action='append', default=[],
                    help='also include this optional-dependency group')
    args = ap.parse_args(argv)

    data = tomllib.loads(Path(args.pyproject).read_text(encoding='utf-8'))
    project = data['project']
    requirements = list(project.get('dependencies', []))
    optional = project.get('optional-dependencies', {})
    for extra in args.extra:
        requirements += list(optional.get(extra, []))

    unbounded = []
    # ASCII only: this is written through a redirected stdout, which on
    # Windows is cp1252 and would mangle anything else.
    print('# Generated by scripts/lowest_direct_requirements.py - do not edit.')
    print('# Every direct dependency pinned to the FLOOR of its declared range,')
    print('# so CI exercises the oldest combination this package claims to')
    print('# support rather than only the newest one pip happens to resolve.')
    for requirement in requirements:
        name, floor = floor_of(requirement)
        if floor is None:
            unbounded.append(name)
            continue
        print(f'{name}=={floor}')

    for name in unbounded:
        print(f'# {name}: no lower bound declared — nothing to pin',
              file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
